"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!ip0+z@)2y0d06@n#!5_g=snd9245c38!&-dscn1=5mp5@egxf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'students',  # <--- ithu thaan un app, practice illa
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# CORS — allows the React dev server (port 5173) to call this API
CORS_ALLOW_ALL_ORIGINS = True
# or, more restrictive:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]


# =====================================================================
# DJANGO REST FRAMEWORK — auth + throttling
# =====================================================================
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/hour',
        'user': '100/hour',
        'login': '10/hour',
        'otp': '5/hour',
    },
}


# =====================================================================
# AUTH — encryption keys for encrypted email/phone storage
# (already generated for you — safe to use for local development)
# =====================================================================
EMAIL_ENCRYPTION_KEY = 'VcMmIgjVvqQtoslEG-_GBx1Eo3NWmGP0vfE_odIf6qQ='
EMAIL_HASH_SECRET = '2fe3e5d8c62a8bb3f30f0fe646fd1ac91c056925a6691fb06f7029a140786c2f'


# =====================================================================
# AUTH — password hashing (bcrypt first)
# =====================================================================
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# =====================================================================
# AUTH — email backend
# For now, OTP/reset-link emails print to this terminal instead of
# actually being sent, so you can test register/login without setting
# up Gmail SMTP first. Switch to real SMTP later — see notes at the
# bottom of this file.
# =====================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'vidhv501@gmail.com'
EMAIL_HOST_PASSWORD = 'stnajmrsuvvtdxnq'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = 'noreply@interviewpro.local'


# =====================================================================
# AUTH — JWT tokens
# =====================================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,   # True requires 'rest_framework_simplejwt.token_blacklist' app
}


# =====================================================================
# Frontend URL — used to build password-reset links emailed to users
# =====================================================================
FRONTEND_URL = 'http://localhost:5173'


# =====================================================================
# LATER — once register/login/OTP all work with the console backend
# above, switch to real Gmail so OTP emails actually arrive in inboxes:
#
#   1. Go to https://myaccount.google.com/apppasswords
#   2. Generate an "App Password" for your Gmail account (needs 2-Step
#      Verification turned on first)
#   3. Replace the EMAIL_BACKEND block above with:
#
#       EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#       EMAIL_HOST = 'smtp.gmail.com'
#       EMAIL_PORT = 587
#       EMAIL_USE_TLS = True
#       EMAIL_HOST_USER = 'youraddress@gmail.com'
#       EMAIL_HOST_PASSWORD = 'the 16-character app password'
#       DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# =====================================================================